import { StyleSheet } from 'react-native';
import { useTheme } from '../context/ThemeContext';
import { useMemo } from 'react';
import { Theme } from './theme';

export const useAppStyles = () => {
  const { theme } = useTheme();

  return useMemo(() => {
    return StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: theme.colors.background,
        paddingHorizontal: 20,
        position: 'relative',
        paddingTop: '5%',
      },
      header: {
        paddingTop: theme.spacing.lg,
        paddingBottom: theme.spacing.md,
      },
      headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: theme.spacing.md,
      },
      headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      title: {
        fontSize: 32,
        fontWeight: '700',
        color: theme.colors.text,
        flexShrink: 1,
      },
      subtitle: {
        marginTop: 6,
        fontSize: 14,
        color: theme.colors.textSecondary,
      },
      clearButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: theme.colors.surfaceHighlight,
      },
      clearButtonText: {
        color: theme.colors.danger,
        fontWeight: '600',
      },
      secondaryButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: theme.colors.surfaceHighlight,
        marginRight: 10,
      },
      secondaryButtonText: {
        color: theme.colors.textSecondary,
        fontWeight: '600',
      },
      iconButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: theme.colors.surfaceHighlight,
        alignItems: 'center',
        justifyContent: 'center',
      },
      loadingWrap: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.background,
      },
      inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 10,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
      },
      modalInputRow: {
        marginBottom: 20,
      },
      input: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.text,
        paddingVertical: 8,
      },
      addButton: {
        backgroundColor: theme.colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 12,
      },
      addButtonText: {
        color: theme.colors.primaryText,
        fontWeight: '600',
      },
      emptyState: {
        marginTop: 40,
        alignItems: 'center',
      },
      emptyTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text,
      },
      emptySubtitle: {
        marginTop: 8,
        fontSize: 14,
        color: theme.colors.textSecondary,
        textAlign: 'center',
      },
      listsEmptyState: {
        marginTop: 40,
        alignItems: 'center',
        paddingHorizontal: 16,
      },
      list: {
        paddingTop: 16,
        paddingBottom: 140,
      },
      listCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
      },
      listCardMain: {
        marginBottom: 10,
      },
      listCardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.text,
      },
      listCardTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      listCardSharedIcon: {
        marginLeft: 8,
      },
      listCardMeta: {
        marginTop: 4,
        fontSize: 13,
        color: theme.colors.textSecondary,
      },
      listCardActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
      },
      listCardActionButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: theme.colors.surfaceHighlight,
        marginLeft: 8,
      },
      listCardActionText: {
        color: theme.colors.textSecondary,
        fontWeight: '600',
      },
      listCardDeleteText: {
        color: theme.colors.danger,
        fontWeight: '600',
      },
      completedSection: {
        marginTop: 4,
      },
      completedHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.colors.surfaceHighlight,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
        marginBottom: 12,
      },
      completedTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.textSecondary,
      },
      completedChevron: {
        fontSize: 18,
        color: theme.colors.textSecondary,
      },
      listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
      },
      checkbox: {
        width: 28,
        height: 28,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
      },
      checkboxChecked: {
        backgroundColor: theme.colors.primary,
      },
      checkmark: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
      },
      itemTextWrap: {
        flex: 1,
      },
      itemText: {
        fontSize: 16,
        color: theme.colors.text,
      },
      itemTextPurchased: {
        color: theme.colors.textSecondary,
        textDecorationLine: 'line-through',
      },
      deleteButton: {
        paddingVertical: 6,
        paddingHorizontal: 6,
        opacity: 0.5,
      },
      quantityWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 10,
        backgroundColor: theme.colors.surfaceHighlight,
        borderRadius: 8,
        paddingHorizontal: 4,
        paddingVertical: 2,
      },
      quantityButton: {
        paddingHorizontal: 8,
        paddingVertical: 4,
      },
      quantityText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        minWidth: 20,
        textAlign: 'center',
      },
      fab: {
        position: 'absolute',
        right: 20,
        bottom: 28,
        width: 58,
        height: 58,
        borderRadius: 29,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
      },
      fabIcon: {
        fontSize: 32,
        color: theme.colors.primaryText,
        fontWeight: '600',
        marginTop: -2,
      },
      modalContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: theme.colors.backdrop,
      },
      modalBackdrop: {
        flex: 1,
      },
      modalPanel: {
        height: '82%',
        backgroundColor: theme.colors.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 20,
      },
      modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 14,
      },
      modalContent: {
        flex: 1,
      },
      selectedTray: {
        backgroundColor: theme.colors.surfaceHighlight,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 12,
      },
      selectedTrayHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
      },
      selectedTrayTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.text,
      },
      selectedClearButton: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: theme.colors.surfaceHighlight,
      },
      selectedClearText: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
      },
      selectedEmptyText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
      },
      overlaySectionsScroll: {
        flex: 1,
      },
      overlaySectionsContent: {
        paddingBottom: 20,
      },
      modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.text,
      },
      modalCloseButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: theme.colors.surfaceHighlight,
      },
      modalCloseText: {
        color: theme.colors.text,
        fontWeight: '600',
      },
      overlaySection: {
        backgroundColor: theme.colors.surfaceHighlight,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 14,
        marginBottom: 10,
        overflow: 'hidden',
      },
      overlaySectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 14,
        paddingVertical: 12,
      },
      overlaySectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.text,
      },
      overlaySectionChevron: {
        fontSize: 20,
        fontWeight: '500',
        color: theme.colors.text,
        lineHeight: 20,
      },
      overlaySectionBody: {
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
        paddingHorizontal: 14,
        paddingVertical: 12,
      },
      recentsHint: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginBottom: 10,
      },
      recentsEmpty: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: 2,
      },
      tagsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
      },
      overlayPlaceholderText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
      },
      tag: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
        marginRight: 10,
        marginBottom: 10,
      },
      selectedTag: {
        marginBottom: 8,
      },
      tagText: {
        fontSize: 14,
        color: theme.colors.text,
        fontWeight: '600',
      },
      tagTextSelected: {
        color: '#ffffff',
      },
      addSelectedButton: {
        marginTop: 12,
        backgroundColor: theme.colors.primary,
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
      },
      addSelectedButtonDisabled: {
        backgroundColor: theme.colors.surfaceHighlight, // or a disabled color
      },
      addSelectedButtonText: {
        color: theme.colors.primaryText,
        fontSize: 16,
        fontWeight: '700',
      },
      settingsPopoverBackdrop: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 5,
      },
      settingsPopover: {
        position: 'absolute',
        top: 80,
        right: 20,
        minWidth: 180,
        borderRadius: 12,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
        zIndex: 6,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 8,
      },
      settingsPopoverButton: {
        paddingHorizontal: 12,
        paddingVertical: 11,
      },
      settingsPopoverButtonText: {
        color: theme.colors.text,
        fontWeight: '600',
      },
      settingsPopoverDangerText: {
        color: theme.colors.danger,
      },
      settingsPopoverDivider: {
        height: 1,
        backgroundColor: theme.colors.border,
      },
      nameModalContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
        backgroundColor: theme.colors.backdrop,
      },
      nameModalBackdrop: {
        ...StyleSheet.absoluteFillObject,
      },
      nameModalCard: {
        width: '100%',
        borderRadius: 18,
        backgroundColor: theme.colors.background,
        paddingHorizontal: 16,
        paddingTop: 18,
        paddingBottom: 14,
        borderWidth: 1,
        borderColor: theme.colors.border,
      },
      nameModalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.text,
        marginBottom: 12,
      },
      nameModalInput: {
        backgroundColor: theme.colors.inputBackground,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        color: theme.colors.text,
      },
      nameModalError: {
        marginTop: 8,
        fontSize: 13,
        color: theme.colors.danger,
      },
      nameModalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 14,
      },
      nameModalCancelButton: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: theme.colors.surfaceHighlight,
        marginRight: 8,
      },
      nameModalCancelText: {
        color: theme.colors.text,
        fontWeight: '600',
      },
      nameModalSubmitButton: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: theme.colors.primary,
      },
      nameModalSubmitText: {
        color: theme.colors.primaryText,
        fontWeight: '700',
      },
      // Settings Screen specific styles
      settingsSection: {
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        marginBottom: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: theme.colors.border,
      },
      settingsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
      },
      settingsRowLast: {
        borderBottomWidth: 0,
      },
      settingsLabel: {
        fontSize: 16,
        fontWeight: '500',
        color: theme.colors.text,
      },
      settingsValue: {
        fontSize: 16,
        color: theme.colors.textSecondary,
      },
      settingsSectionTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginBottom: 8,
        marginLeft: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
      },
      authPlaceholder: {
        padding: 20,
        alignItems: 'center',
      },
      authButton: {
        backgroundColor: theme.colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        minWidth: 120,
        alignItems: 'center',
        marginVertical: 8,
      },
      authButtonSecondary: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: theme.colors.border,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        minWidth: 120,
        alignItems: 'center',
        marginVertical: 8,
      },
      authButtonText: {
        color: theme.colors.primaryText,
        fontWeight: '600',
      },
      authButtonTextSecondary: {
        color: theme.colors.text,
        fontWeight: '600',
      },
    });
  }, [theme]);
};
