import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f4f0',
    paddingHorizontal: 20,
    position: 'relative',
    paddingTop: '5%',
  },
  header: {
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1f1f1f',
  },
  subtitle: {
    marginTop: 6,
    fontSize: 14,
    color: '#6b6b6b',
  },
  clearButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
  },
  clearButtonText: {
    color: '#9a3d3d',
    fontWeight: '600',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  modalInputRow: {
    marginBottom: 20,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#222222',
    paddingVertical: 8,
  },
  addButton: {
    backgroundColor: '#1f7a5a',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  emptyState: {
    marginTop: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2d2d2d',
  },
  emptySubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: '#7b7b7b',
  },
  list: {
    paddingTop: 16,
    paddingBottom: 140,
  },
  completedSection: {
    marginTop: 4,
  },
  completedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#efe6df',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
  },
  completedTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4a4a4a',
  },
  completedChevron: {
    fontSize: 18,
    color: '#6a6a6a',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#1f7a5a',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#1f7a5a',
  },
  checkmark: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  itemTextWrap: {
    flex: 1,
  },
  itemText: {
    fontSize: 16,
    color: '#2a2a2a',
  },
  itemTextPurchased: {
    color: '#9a9a9a',
    textDecorationLine: 'line-through',
  },
  deleteButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
  },
  deleteButtonText: {
    color: '#9a3d3d',
    fontWeight: '600',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#1f7a5a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  fabIcon: {
    fontSize: 32,
    color: '#ffffff',
    fontWeight: '600',
    marginTop: -2,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalPanel: {
    height: '82%',
    backgroundColor: '#fdfaf6',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalContent: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f1f1f',
  },
  modalCloseButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
  },
  modalCloseText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  recentsHeader: {
    marginBottom: 10,
  },
  recentsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2a2a2a',
  },
  recentsHint: {
    marginTop: 4,
    fontSize: 12,
    color: '#7a7a7a',
  },
  recentsEmpty: {
    fontSize: 14,
    color: '#7a7a7a',
    marginTop: 12,
  },
  recentsScroll: {
    flex: 1,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 20,
  },
  tag: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f0e6df',
    borderWidth: 1,
    borderColor: '#e2d4c6',
    marginRight: 10,
    marginBottom: 10,
  },
  tagText: {
    fontSize: 14,
    color: '#4a4a4a',
    fontWeight: '600',
  },
  tagTextSelected: {
    color: '#ffffff',
  },
  addSelectedButton: {
    marginTop: 12,
    backgroundColor: '#1f7a5a',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  addSelectedButtonDisabled: {
    backgroundColor: '#b9c7bf',
  },
  addSelectedButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
});
