import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f4f0',
    paddingHorizontal: 20,
    position: 'relative',
    paddingTop: '5%',
  },
  header: {
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1f1f1f',
    flexShrink: 1,
  },
  subtitle: {
    marginTop: 6,
    fontSize: 14,
    color: '#6b6b6b',
  },
  clearButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
  },
  clearButtonText: {
    color: '#9a3d3d',
    fontWeight: '600',
  },
  secondaryButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
    marginRight: 10,
  },
  secondaryButtonText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#f0e6df',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  modalInputRow: {
    marginBottom: 20,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#222222',
    paddingVertical: 8,
  },
  addButton: {
    backgroundColor: '#1f7a5a',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  emptyState: {
    marginTop: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2d2d2d',
  },
  emptySubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: '#7b7b7b',
    textAlign: 'center',
  },
  listsEmptyState: {
    marginTop: 40,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  list: {
    paddingTop: 16,
    paddingBottom: 140,
  },
  listCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  listCardMain: {
    marginBottom: 10,
  },
  listCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2a2a2a',
  },
  listCardMeta: {
    marginTop: 4,
    fontSize: 13,
    color: '#7a7a7a',
  },
  listCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  listCardActionButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
    marginLeft: 8,
  },
  listCardActionText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  listCardDeleteText: {
    color: '#9a3d3d',
    fontWeight: '600',
  },
  completedSection: {
    marginTop: 4,
  },
  completedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#efe6df',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
  },
  completedTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4a4a4a',
  },
  completedChevron: {
    fontSize: 18,
    color: '#6a6a6a',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#1f7a5a',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#1f7a5a',
  },
  checkmark: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  itemTextWrap: {
    flex: 1,
  },
  itemText: {
    fontSize: 16,
    color: '#2a2a2a',
  },
  itemTextPurchased: {
    color: '#9a9a9a',
    textDecorationLine: 'line-through',
  },
  deleteButton: {
    paddingVertical: 6,
    paddingHorizontal: 6,
    opacity: 0.5,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#1f7a5a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  fabIcon: {
    fontSize: 32,
    color: '#ffffff',
    fontWeight: '600',
    marginTop: -2,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalPanel: {
    height: '82%',
    backgroundColor: '#fdfaf6',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalContent: {
    flex: 1,
  },
  selectedTray: {
    backgroundColor: '#f6eee7',
    borderWidth: 1,
    borderColor: '#e6d8ca',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  selectedTrayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  selectedTrayTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2a2a2a',
  },
  selectedClearButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#f0e6df',
  },
  selectedClearText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4a4a4a',
  },
  selectedEmptyText: {
    fontSize: 13,
    color: '#767676',
  },
  overlaySectionsScroll: {
    flex: 1,
  },
  overlaySectionsContent: {
    paddingBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f1f1f',
  },
  modalCloseButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
  },
  modalCloseText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  overlaySection: {
    backgroundColor: '#f6eee7',
    borderWidth: 1,
    borderColor: '#e6d8ca',
    borderRadius: 14,
    marginBottom: 10,
    overflow: 'hidden',
  },
  overlaySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  overlaySectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2a2a2a',
  },
  overlaySectionChevron: {
    fontSize: 20,
    fontWeight: '500',
    color: '#4a4a4a',
    lineHeight: 20,
  },
  overlaySectionBody: {
    borderTopWidth: 1,
    borderTopColor: '#e6d8ca',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  recentsHint: {
    fontSize: 12,
    color: '#7a7a7a',
    marginBottom: 10,
  },
  recentsEmpty: {
    fontSize: 14,
    color: '#7a7a7a',
    marginTop: 2,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  overlayPlaceholderText: {
    fontSize: 14,
    color: '#6f6f6f',
  },
  tag: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f0e6df',
    borderWidth: 1,
    borderColor: '#e2d4c6',
    marginRight: 10,
    marginBottom: 10,
  },
  selectedTag: {
    marginBottom: 8,
  },
  tagText: {
    fontSize: 14,
    color: '#4a4a4a',
    fontWeight: '600',
  },
  tagTextSelected: {
    color: '#ffffff',
  },
  addSelectedButton: {
    marginTop: 12,
    backgroundColor: '#1f7a5a',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  addSelectedButtonDisabled: {
    backgroundColor: '#b9c7bf',
  },
  addSelectedButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  settingsPopoverBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
  },
  settingsPopover: {
    position: 'absolute',
    top: 80,
    right: 20,
    minWidth: 180,
    borderRadius: 12,
    backgroundColor: '#fdfaf6',
    borderWidth: 1,
    borderColor: '#efe6df',
    zIndex: 6,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  settingsPopoverButton: {
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  settingsPopoverButtonText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  settingsPopoverDangerText: {
    color: '#9a3d3d',
  },
  settingsPopoverDivider: {
    height: 1,
    backgroundColor: '#efe6df',
  },
  nameModalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  nameModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  nameModalCard: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: '#fdfaf6',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    borderWidth: 1,
    borderColor: '#efe6df',
  },
  nameModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f1f1f',
    marginBottom: 12,
  },
  nameModalInput: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2d4c6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#222222',
  },
  nameModalError: {
    marginTop: 8,
    fontSize: 13,
    color: '#9a3d3d',
  },
  nameModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 14,
  },
  nameModalCancelButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#f0e6df',
    marginRight: 8,
  },
  nameModalCancelText: {
    color: '#4a4a4a',
    fontWeight: '600',
  },
  nameModalSubmitButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#1f7a5a',
  },
  nameModalSubmitText: {
    color: '#ffffff',
    fontWeight: '700',
  },
});
